### ISSUE TITLE
Adding movie Radarr v3

### ISSUE THREAD

**Issue by dipstick1987** [Ulisses1478/teleradarr#1]
Getting this error:
Invalid request Validation failed: 
 -- ProfileId: QualityProfile does not exist

This is in Radarr

**Comment by Ulisses1478** [comment]
Yeah, i did not think in this, I will update soon so in the config file, you will be able to specify the profile number.

**Comment by Ulisses1478** [comment]
Fixed with last commit, an update will be available soon
