### ISSUE TITLE
Incorrect file location.

### ISSUE THREAD

**Issue by dipstick1987** [Ulisses1478/teleradarr#2]
The bot is now working with Radarr v3 but it seems to be pulling the wrong location.

The location is /media/Movies but the movies are importing as /media/movies which is leading to errors and things not importing.

I assume there is logic to lowercase everything but I could be wrong.

**Comment by Ulisses1478** [comment]
What radarr container are you using?

**Comment by Ulisses1478** [comment]
Forget the last, question. I will add a optional docker variable that you can change the location mannualy

**Comment by Ulisses1478** [comment]
Update is done, check the readme for the new variables or download the new template on unraid
